### ISSUE TITLE
server-simple: service status logged for host system and not for system under test

### ISSUE THREAD

**Issue by paride** [canonical/server-test-scripts#188]
@cpaelzer looks like we have issues here:

https://github.com/canonical/server-test-scripts/blob/f444e6e9603d490564a306401fd1e693c6eb59aa/metric-server-simple/metric-server-simple.sh#L194

1. We're executing it on the host system (Jenkins node) and not in the container, right? We want a `cexec` there I believe. Let's also add `--no-pager`.
2. The command can return nonzero, so we need a `|| true`.
3. Can we save that to file instead of printing to stdout? The output is very long and makes the Jenkins consolelog even more difficult to read. If you are +1 on saving to file we'll also need to archive it, adding it to the `archiveArtifacts('results-*.json')` line in the JJB definitions

**Comment by cpaelzer** [comment]
yeah, we came to the same conclusion.
I had all but Cexec ready, adding that to #190
