### ISSUE TITLE
Tweak instance types for bootspeed testing

### ISSUE THREAD

**Issue by rcj4747** [canonical/server-test-scripts#37]
ARM:

- Add a [Graviton2](https://aws.amazon.com/ec2/graviton/) instance type to testing in addition to a1 which is the first generation.  The performance change with graviton 2 is significant and these newer instance types would better capture user experience.  My suggestion would be m6g.large

AMD64:

You are using burstable instance types t[2|3].large which are inappropriate for consistent boot speed testing.

- These instances use shared CPUs with a performance budget, there is a grace period for boot but if you exceed this budget then the boot speed will skew more as boot time increases.
- When launching multiple burstable instances of t2 and t3 types that are short lived (like your tests) we have observed a penalty applied when more burstable instances are launched.  This means that if you test one release after the next, the last release could be penalized by the prior runs.  This is based on observation and could be a function to curb abuse of the cloud platform but it does not appear to be documented.

Based on these 2 thing I would suggest an instance type that isn't over-committed with a cpu burst budget like an Intel-based m5.large to replace t2/t3 or if you want AMD you could use m5a.large.  Given the need for performance-impacting patches on Intel after repeated speculative execution related vulnerabilities you might be better off with m5a.large if you want to compare boot speed numbers with a broad time horizon as AMD has fared better so far.

**Comment by raharper** [comment]
> Based on these 2 thing I would suggest an instance type that isn't over-committed with a cpu burst budget like an Intel-based m5.large to replace t2/t3 or if you want AMD you could use m5a.large. Given the need for performance-impacting patches on Intel after repeated speculative execution related vulnerabilities you might be better off with m5a.large if you want to compare boot speed numbers with a broad time horizon as AMD has fared better so far.

A couple of comments.

1) The most launched instance type is highly likely to be a burstable "free tier" instance; so while we will see variable boot speed; _so_ will our users.   This also is relevant to your comment re: Intel perf patches.
2) The primary metric we're after is *first* boot speed; so if there's a grace period for boot; we're taking advantage of that; hopefully less likely to skew results.
3) w.r.t the burstable penalty, is the per account? or would launching in different regions when running sequences of tests help?
4) I'm +1 on adding non-burstable instance types for a more consistent resource w.r.t potential throttling.

**Comment by rcj4747** [comment]
> 1. The most launched instance type is highly likely to be a burstable "free tier" instance; so while we will see variable boot speed; _so_ will our users.   This also is relevant to your comment re: Intel perf patches.

Not that they won't be popular but "most launched" is purely conjecture and orthogonal to the debate.  Burstable instances have unpredictable performance and we're trying to view bootspeed over time, for that to be useful as a metric it needs to be repeatable.  I don't see an argument here that performing the measurement on a predictable instance type and using that the direct engineering effort would not also provide meaningful benefits to users of burstable instances.

> 2. The primary metric we're after is _first_ boot speed; so if there's a grace period for boot; we're taking advantage of that; hopefully less likely to skew results.

You might running over the grace period was my point and then the impact of slower boot becomes non-linear in your data which exaggerates the impact.  That might cause incorrect prioritization of work and it might send someone looking for a way to get back 10 seconds of boot that really is only 3 seconds of scheduled CPU time because you were penalized after X seconds into boot.  Someone steeped in this may have all this in their head when viewing the data, but I think that's unreasonable to expect and that makes the results less accessible.

> 3. w.r.t the burstable penalty, is the per account? or would launching in different regions when running sequences of tests help?

No idea unfortunately, it's undocumented behaviour based on our observations and certainly subject to change.  Just know that we've seen issues with using burstable CPUs for short test runs resulting in subsequent instance launches to be impacted by prior instances within some window of time.  I think this is the nail in the coffin for using burstable instances for this data collection, you can't know if launching a few instances to collect stats aren't impacted by instances you've just been running to collect data for another release.  In that case you're not seeing something that gives you useful insight into what end-users would see at least with respect to the boot behaviour you can affect as an Ubuntu developer.

> 4. I'm +1 on adding non-burstable instance types for a more consistent resource w.r.t potential throttling.

**Comment by raharper** [comment]
> Not that they won't be popular but "most launched" is purely conjecture and orthogonal to the debate. 

It's speaks directly to the issue;  If you optimize something that no one uses; what's the point?  It's not conjecture.  I'm happy to defer to any more direct information on what a better popular instance type that users would encounter.

> I don't see an argument here that performing the measurement on a predictable instance type and using that the direct engineering effort would not also provide meaningful benefits to users of burstable instances.

One will only know if the effort has an impact on the burstable instances if we capture the data;  it's reasonable to collect from *both*.

We've got data; it's worth looking at it to see how much variance we have to date.   In my scale testing (groups of up to 50 instances in parallel), I've not found significant (for boot speed in seconds resolution) variability.  That does not preclude it showing up; but to claim that improvements in one path affect the other; we certainly have to measure (even if it's going to have some variance); and we disclose the variance with the result.

**Comment by paride** [comment]
Hi @rcj4747, I'm adding the jobs to measure `m6g.large`. On amd64: we already measure `c5.large` in addition to `t{2,3}.large`, which is fixed performance.

**Comment by rcj4747** [comment]
Fantastic, thanks @paride.  This is timely as we're working on snap preseed optimizations in devel and then backports to supported releases.

**Comment by paride** [comment]
@rcj4747 the m6g.large measurements are now in place and the graphs are showing up. Thanks for the suggestion of adding them.
